import{S as h,a as y,i as d}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();function p(a){const{largeImageURL:t,webformatURL:i,tags:l,likes:e,views:o,comments:n,downloads:u}=a;return`<li class="photo-card">
  <a class="gallery-link" href="${t}">
    <img
      class="gallery-image"
      src="${i}"
      alt="${l}"
    />
  </a>
  <div class="info">
        <p>Likes: <span class="likes">${e}</span></p>
        <p>Views: <span class="views">${o}</span></p>
        <p>Comments: <span class="comments">${n}</span></p>
        <p>Downloads: <span class="downloads">${u}</span></p>
      </div>
</li>`}function L(){r.gallery.classList.add("hidden"),r.loader.classList.remove("hidden")}function c(){r.loader.classList.add("hidden"),r.gallery.classList.remove("hidden")}const r={form:document.querySelector(".search-form"),input:document.querySelector("#input"),button:document.querySelector(".search-button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-box"),loadElem:document.querySelector(".js-loader"),btnLoadMore:document.querySelector(".js-btn-load")},b=new h(".gallery a",{captionsData:"alt",captionDelay:250});async function m(a,t){const i="https://pixabay.com/api/",e={key:"49003886-a24f9c3a0fd607f8ed8b1fc56",q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:t};try{const n=(await y.get(i,{params:e})).data;if(n.hits.length===0)return d.info({title:"No Results",message:"No images found for your search.",position:"topRight"}),c(),r.input.value="",null;r.input.value="";const u=n.hits.map(p).join("");return r.gallery.innerHTML=u,c(),b.refresh(),{images:n.hits,totalHits:n.totalHits}}catch{return c(),d.error({title:"Error",message:"❌ Error fetching images. Please try again!",position:"topRight"}),null}}const s={query:"",page:1,total:0};r.form.addEventListener("submit",async a=>{if(a.preventDefault(),s.query=a.target.elements.input.value.trim(),s.page=1,L(),!s.query){d.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),c();return}const t=await m(s.query,s.page);t&&(s.total=t.totalHits,f())});r.btnLoadMore.addEventListener("click",async()=>{g(),q(),s.page+=1;const t=(await m(s.query,s.page)).images.map(p).join("");r.gallery.insertAdjacentHTML("beforeend",t),f(),w(),E()});function f(){const t=Math.ceil(s.total/40);s.page>=t?(g(),d.info({title:"Info",message:"We are sorry, but you have reached the end of search results",position:"topRight"})):v()}function v(){r.btnLoadMore.classList.remove("hidden")}function g(){r.btnLoadMore.classList.add("hidden")}function q(){r.loadElem.classList.remove("hidden")}function w(){r.loadElem.classList.add("hidden")}function E(){const t=r.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:t*2})}
//# sourceMappingURL=index.js.map
