import{a as b,i as c,S as L}from"./assets/vendor-D0cagnvz.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function m(t,a,o){const i="https://pixabay.com/api/",e={key:"49003886-a24f9c3a0fd607f8ed8b1fc56",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:a,per_page:o};return(await b.get(i,{params:e})).data}function x(t){const{largeImageURL:a,webformatURL:o,tags:i,likes:e,views:r,comments:l,downloads:y}=t;return`<li class="photo-card">
  <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${o}"
      alt="${i}"
    />
  </a>
  <div class="info">
        <p>Likes: <span class="likes">${e}</span></p>
        <p>Views: <span class="views">${r}</span></p>
        <p>Comments: <span class="comments">${l}</span></p>
        <p>Downloads: <span class="downloads">${y}</span></p>
      </div>
</li>`}function u(t){return t.map(x).join("")}const n={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),btnNext:document.querySelector(".gallery-btn"),loader:document.querySelector(".loader")};let d;const s={message:"",page:null,total:1,perPage:40};g();n.form.addEventListener("submit",w);async function w(t){f(),t.preventDefault(),n.gallery.innerHTML="";const a=t.target.elements.search.value.trim();s.message=a,s.page=1;try{const o=await m(s.message,s.page,s.perPage);if(o.hits.length===0)g(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"});else{const i=u(o.hits);n.gallery.innerHTML=i,s.total=o.totalHits,p(),h(),d=new L(".gallery a")}}catch(o){n.gallery.innerHTML="",c.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"}),console.log(o)}t.target.reset()}n.btnNext.addEventListener("click",async()=>{g(),f(),s.page+=1;try{const t=await m(s.message,s.page,s.perPage),a=u(t.hits);n.gallery.insertAdjacentHTML("beforeend",a),d.refresh(),p(),h(),v()}catch{c.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"}),p()}});function f(){n.loader.classList.remove("hidden")}function p(){n.loader.classList.add("hidden")}function P(){n.btnNext.style.display=""}function g(){n.btnNext.style.display="none"}function h(){const t=Math.ceil(s.total/s.perPage);s.page>=t||s.total<s.perPage?(g(),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):P()}function v(){const a=n.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({behavior:"smooth",top:a*2})}
//# sourceMappingURL=index.js.map
